# Generated by Django 6.0.3 on 2026-05-07 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_price_max_product_price_min_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='message',
            name='delivery_status',
            field=models.CharField(default='sent', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='negotiated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='negotiated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_approved', 'Order Approved'), ('order_rejected', 'Order Rejected'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('new_message', 'New Message'), ('verification_status', 'Verification Status Updated'), ('negotiation_update', 'Negotiation Update')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('farmer_reviewing', 'Farmer Reviewing'), ('negotiating', 'Negotiating'), ('approved', 'Approved'), ('awaiting_payment', 'Awaiting Payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('dispatched', 'Dispatched'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='FarmerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_image', models.ImageField(upload_to='verification_docs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.OneToOneField(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='verification_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gateway', models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti')], max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('response_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.order')),
            ],
        ),
    ]
