# Generated by Django 6.0.3 on 2026-05-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_message_options_message_delivery_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='category',
            name='is_active_pricing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
        ),
        migrations.AddField(
            model_name='category',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
