# Generated by Django 6.0.3 on 2026-05-07 23:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='produce_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('KG', 'KG'), ('Gram', 'Gram'), ('Dozen', 'Dozen'), ('Piece', 'Piece'), ('Liter', 'Liter'), ('Sack', 'Sack'), ('Bundle', 'Bundle'), ('Tray', 'Tray')], default='KG', max_length=50),
        ),
    ]
