# Generated by Django 6.0.3 on 2026-05-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('farmer_reviewing', 'Farmer Reviewing'), ('negotiating', 'Negotiating'), ('approved', 'Approved'), ('awaiting_payment', 'Awaiting Payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('dispatched', 'Dispatched'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('received', 'Received'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
