# Generated by Django 6.0.3 on 2026-05-09 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_admin_listed',
            field=models.BooleanField(default=False, help_text='Check if this product is listed by admin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='farmer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'farmer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
