# Generated by Django 6.0.3 on 2026-05-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_is_admin_listed_alter_product_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_approved', 'Order Approved'), ('order_rejected', 'Order Rejected'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('new_message', 'New Message'), ('verification_status', 'Verification Status Updated'), ('negotiation_update', 'Negotiation Update'), ('product_approved', 'Product Approved'), ('product_rejected', 'Product Rejected')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('available', 'Available'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued')], default='available', max_length=20),
        ),
    ]
