# Generated by Django 6.0.3 on 2026-05-09 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_approved', 'Order Approved'), ('order_rejected', 'Order Rejected'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('new_message', 'New Message'), ('verification_status', 'Verification Status Updated'), ('negotiation_update', 'Negotiation Update')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued')], default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='FarmerApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='item_approvals', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_approvals', to='core.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_approval', to='core.orderitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('order_item', 'farmer')},
            },
        ),
    ]
