# Generated by Django 6.0.3 on 2026-05-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='shelf_life_days',
            field=models.PositiveIntegerField(default=7, help_text='Average days this type of produce stays fresh.'),
        ),
        migrations.DeleteModel(
            name='FarmerApproval',
        ),
    ]
