# Generated by Django 4.2.11 on 2026-06-02 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_category_shelf_life_days_delete_farmerapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('negotiating', 'Negotiating'), ('rejected', 'Rejected'), ('dispatched', 'Dispatched'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('paid', 'Paid'), ('received', 'Received Confirmation'), ('other', 'Other')], max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_actions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
