# Generated by Django 4.2.11 on 2026-05-29 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_category_shelf_life_days_delete_farmerapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=False)),
                ('order_notifications', models.BooleanField(default=True)),
                ('message_notifications', models.BooleanField(default=True)),
                ('product_notifications', models.BooleanField(default=True)),
                ('payment_notifications', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_placed', 'Order Placed'), ('order_approved', 'Order Approved'), ('order_rejected', 'Order Rejected'), ('order_cancelled', 'Order Cancelled'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_returned', 'Order Returned'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('payment_pending', 'Payment Pending'), ('refund_processed', 'Refund Processed'), ('new_message', 'New Message'), ('message_seen', 'Message Seen'), ('new_order_received', 'New Order Received'), ('product_low_stock', 'Product Low Stock'), ('product_out_of_stock', 'Product Out of Stock'), ('product_approved', 'Product Approved'), ('product_rejected', 'Product Rejected'), ('order_urgency_alert', 'Order Urgency Alert'), ('pending_verification_alert', 'Pending Verification Alert'), ('expiring_product_alert', 'Expiring Product Alert'), ('negotiation_started', 'Negotiation Started'), ('negotiation_update', 'Negotiation Update'), ('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('offer_rejected', 'Offer Rejected'), ('delivery_assigned', 'Delivery Assigned'), ('delivery_delayed', 'Delivery Delayed'), ('verification_status', 'Verification Status Updated'), ('account_suspended', 'Account Suspended'), ('system_announcement', 'System Announcement'), ('report_received', 'Report Received')], db_index=True, max_length=50)),
                ('target_role', models.CharField(choices=[('admin', 'Admin'), ('farmer', 'Farmer'), ('customer', 'Customer'), ('all', 'All Users')], default='all', help_text='Target role for the notification', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('redirect_url', models.CharField(blank=True, help_text='URL to redirect when notification is clicked', max_length=500, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.product')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='notificatio_created_ae6ed6_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_d8746a_idx')],
            },
        ),
    ]
