# Generated by Django 4.2.11 on 2026-06-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_read_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_approved', 'Order Approved'), ('order_rejected', 'Order Rejected'), ('order_cancelled', 'Order Cancelled'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_returned', 'Order Returned'), ('order_received', 'Order Received'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('payment_pending', 'Payment Pending'), ('refund_processed', 'Refund Processed'), ('new_message', 'New Message'), ('message_seen', 'Message Seen'), ('new_order_received', 'New Order Received'), ('product_low_stock', 'Product Low Stock'), ('product_out_of_stock', 'Product Out of Stock'), ('product_approved', 'Product Approved'), ('product_rejected', 'Product Rejected'), ('order_urgency_alert', 'Order Urgency Alert'), ('pending_verification_alert', 'Pending Verification Alert'), ('expiring_product_alert', 'Expiring Product Alert'), ('negotiation_started', 'Negotiation Started'), ('negotiation_update', 'Negotiation Update'), ('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('offer_rejected', 'Offer Rejected'), ('delivery_assigned', 'Delivery Assigned'), ('delivery_delayed', 'Delivery Delayed'), ('verification_status', 'Verification Status Updated'), ('account_suspended', 'Account Suspended'), ('system_announcement', 'System Announcement'), ('report_received', 'Report Received')], db_index=True, max_length=50),
        ),
    ]
